### ISSUE TITLE
Add "step_kwargs" as an explicit argument to MCKernel constructor

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/smol#205]
**Is your feature request related to a problem? Please describe.**
When initializing MCKernel, all **kwargs are passed to the constructor of a MCUsher, which is not good. In the child class of MCKernel, we may want more parameters to initialize MCKernel. For example, for multi-try monte-carlo, we need to specify the number of tries per MC step, therefore one additional parameter is needed for that. Suppose we call it parameter self.k. Of course, you can check whether **kwargs includes an argument 'k' when you construct MultitryKernel, and you set an Exception check to enforce that. But in the end, this does not seem very standard.

**Describe the solution you'd like**
Add step_kwargs as an explicit keyword into the constructor of MCKernel. This will help us separate keyword arguments needed by MCUsher and MCKernel sub-classes. This will also match our design in bias constructor better, as we explicitly specify "bias_kwargs" for any bias.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by lbluque** [comment]
Hi @qchempku2017 thanks for raising this. I agree it will be better to address this now rather than too far down the road.

Let's talk about this in person, because I am not sure if the better approach is to pass the instantiated classes (ie Bias or Usher) directly to the Kernel constructor, rather than passing strings to generate these.

**Comment by lbluque** [comment]
Perhaps its better to pass instances of the Usher and the Bias to the Kernel constructor.

**Comment by lbluque** [comment]
@qchempku2017  What did we decide on this? do we still need this?

**Comment by qchempku2017** [comment]
> @qchempku2017 What did we decide on this? do we still need this?

For the time being I seem to be okay living with this. When I proposed this I was a bit confused with the usage of Kwargs. Indeed, any additional kwarg that appears in the __init__ arguments of a MCKernel should have been captured when calling the init function, then the rest of the arguments that can not be recognized can all be considered as arguments to MCUsher, and then packed into **kwargs and passed down. 

This thread is very stupid. We should close this as resolved.
