### ISSUE TITLE
spglib >2.0.0 breaks symmetry tests

### ISSUE THREAD

**Issue by lbluque** [CederGroupHub/smol#285]
spglib >2.0.0 is breaking unit-tests.

Before we had pinned to a lower version, but the newest versions of pymatgen now have spglib >2 as a requirement.

We should investigate the discrepancy and open an issue in pymatgen and/or spglib accordingly.

**Comment by lbluque** [comment]
See materialsproject/pymatgen#2725

**Comment by qchempku2017** [comment]
This issue seems to have been fixed in pymatgen=2022.11.7. Please close this issue when pymatgen==2022.11.7 is available in pypi.
