### ISSUE TITLE
Error when loading SampleContainer from hdf5: "accepted" key of the trace is a Nonetype

### ISSUE THREAD

**Issue by kamronald** [CederGroupHub/smol#325]
I am unable to load my sample containers from the hdf5 format using from_hdf5() function of SampleContainer. The error is TypeError: 'NoneType' object is not subscriptable
This arises when creating the Trace object from the saved hdf5 file, because the "accepted" key in the trace is a Nonetype, so cannot be indexed.

## Possible Solution

Create an exception for creating Trace that skips the key when its value is Nonetype.

## Steps to Reproduce

1. Loading a sample container from hdf5.
2.

**Comment by kamronald** [comment]
After making a test sampler and streaming samples to a new h5 file, I see that the issue does not happen. So it may be because of backwards incompatibility with old sample containers

**Comment by lbluque** [comment]
Thanks @kamronald! can you send me the samplecontainer that has issues over email?

**Comment by lbluque** [comment]
closing. feel free to re-open if the problem persists
