### ISSUE TITLE
Strange datatype issues after PR #358

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/smol#385]
Weird datatype issues associated with smol.util.container classes appear after PR #358 .

## Current Behavior

(1) When trying to test test_cofe/test_cluster_utils.py, the following issues pops up on my local computer (but not on CI):

```test_utils\test_cluster_utils.py:11 (test_int_container[IntArray1DContainer-1])
IntArrayContainer = <class 'smol.utils.cluster.container.IntArray1DContainer'>
dim = 1, rng = Generator(PCG64) at 0x25C6BA67660
​
    @pytest.mark.parametrize(
        "IntArrayContainer, dim", [(IntArray1DContainer, 1), (IntArray2DContainer, 2)]
    )
    def test_int_container(IntArrayContainer, dim, rng):
        arrays = tuple(
            rng.integers(1, 5, size=dim * (rng.integers(1, 5),)) for _ in range(10)
        )
>       container = IntArrayContainer(arrays)
​
test_cluster_utils.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
smol\utils\cluster\container.pyx:230: in smol.utils.cluster.container.IntArray1DContainer.__cinit__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
​
>   ???
E   ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
​
smol\utils\cluster\container.pyx:251: ValueError
```

The tests were performed on a 64bit Windows 11 platform, with numpy=1.24.4.

The datatype generated by my random number generator was "long long" (int64, maybe?) rather than "long"(probably int32?). This could require an explicit specification in either the container class or the test to make the containers always store one of the types.

(2) When trying to initialize ClusterExpansion with a coef array that contains int, the following error pops up:

```self = <[UFuncTypeError(<ufunc 'divide'>, 'same_kind', dtype('float64'), dtype('int32'), 2) raised in repr()] ClusterExpansion object at 0x1856f0558b0>
    @cached_property
    def eci(self):
        """Get the ECI for the cluster expansion.
    
        This just divides coefficients by the corresponding multiplicities.
        External terms are dropped since their fitted coefficients do not
        represent ECI.
        """
        num_ext_terms = len(self._subspace.external_terms)  # check for extra terms
        coefs = self.coefs[:-num_ext_terms] if num_ext_terms else self.coefs[:]
        eci = coefs.copy()
>       eci /= self._subspace.function_total_multiplicities
E       numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
..\venv\lib\site-packages\smol\cofe\expansion.py:182: UFuncTypeError
```

This can be temporarily solved by force transforming coefs array to float type, or do as suggested here:
[Discussion on stackoverflow](https://stackoverflow.com/questions/38673531/numpy-cannot-cast-ufunc-multiply-output-from-dtype
)

**Comment by lbluque** [comment]
1) For the first issue, can you look into the actual data type being generated in the `arrays` variable and see if you force it to be of type int by explicitly adding `dtype=int` or using [np.int_](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.int_)  (for more info: https://numpy.org/doc/stable/user/basics.types.html)

Seems like np.int64 is long long on windows and long on linux.

**Comment by lbluque** [comment]
2)  For the second issue: You can go ahead and implement the stack-overflow solution you linked.

However, why do you have/want coefficients or eci that are integers?

**Comment by qchempku2017** [comment]
> 1. For the first issue, can you look into the actual data type being generated in the `arrays` variable and see if you force it to be of type int by explicitly adding `dtype=int` or using [np.int_](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.int_)  (for more info: https://numpy.org/doc/stable/user/basics.types.html)
> 
> Seems like np.int64 is long long on windows and long on linux.

array.astype(np.int_) works. np.int_ is int32 on windows, as required by container. Simply enforcing dtype(int) also seems to work. I'll use np.int_.
