### ISSUE TITLE
Default number of threads needs more careful consideration.

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/smol#403]
In ([numthreads.py](https://github.com/CederGroupHub/smol/blob/d00792e7a433d6fb0f0a1504bd05e94b13d28e33/smol/utils/cluster/numthreads.py#L6C6-L6C6)), the default number of threads is set to n_thread=2. This might not be correct when operating on some super-computing systems. 

## Current Behavior

For example, when I tried to initialize a cluster subspace in an atomate2 job performed on lawrencium using the default num_threads=None, atomate2 reported the following error:
Traceback (most recent call last):
  File "/global/home/users/fxie/miniconda3/envs/matsci-kit/lib/python3.9/site-packages/fireworks/core/rocket.py", line 261, in run
    m_action = t.run_task(my_spec)
  File "/global/home/users/fxie/miniconda3/envs/matsci-kit/lib/python3.9/site-packages/jobflow/managers/fireworks.py", line 177, in run_task
    response = job.run(store=store)
  File "/global/home/users/fxie/miniconda3/envs/matsci-kit/lib/python3.9/site-packages/jobflow/core/job.py", line 583, in run
    response = function(*self.function_args, **self.function_kwargs)
  File "/global/home/users/fxie/miniconda3/envs/matsci-kit/lib/python3.9/site-packages/WFacer/jobs.py", line 584, in initialize_document
    subspace = get_cluster_subspace(
  File "/global/home/users/fxie/miniconda3/envs/matsci-kit/lib/python3.9/site-packages/WFacer/preprocessing.py", line 178, in get_cluster_subspace
    space = ClusterSubspace.from_cutoffs(prim, cutoffs=cutoffs, **kwargs)
  File "/global/home/users/fxie/miniconda3/envs/matsci-kit/lib/python3.9/site-packages/smol/cofe/space/clusterspace.py", line 306, in from_cutoffs
    return cls(
  File "/global/home/users/fxie/miniconda3/envs/matsci-kit/lib/python3.9/site-packages/smol/cofe/space/clusterspace.py", line 214, in __init__
    self.num_threads = num_threads
  File "/global/home/users/fxie/miniconda3/envs/matsci-kit/lib/python3.9/site-packages/smol/utils/cluster/numthreads.py", line 39, in __set__
    raise ValueError(f"num_threads cannot be greater than {max_threads}.")
ValueError: num_threads cannot be greater than 1.

## Possible Solution

Currently, I'm forcing WFacer to set num_thread = 1 in order to temporarily address this issue. However, the default num_thread setter must be considered more carefully when smol is to be used on different platforms.

**Comment by lbluque** [comment]
Can you please confirm the output of  `_openmp_effective_numthreads()`   and   `_openmp_effective_numthreads(2)`  in the cluster you are running (you can import it from `smol.utils._openmp_helpers`)

**Comment by qchempku2017** [comment]
I see. In lawrencium submission script, export OMP_NUM_THREADS=1 is forced. I don't know if this can be safely removed because the same setting should be applied across all atomate2 jobs.

**Comment by qchempku2017** [comment]
PS: current standard lawrencium submission script:

`bash

#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --qos=condo_ceder
#SBATCH --time=72:00:00
#SBATCH --account=lr_ceder
#SBATCH --job-name=atomate
#SBATCH --output=atomate-%j.out
#SBATCH --error=atomate-%j.error


#SBATCH --partition=lr5
conda activate matsci-kit
export OMP_NUM_THREADS=1
export OMP_PROC_BIND=true
export OMP_PLACES=threads
module load intel/2020.1.024.par
ulimit -s unlimited

export PATH=$PATH:/global/home/users/fxie/vasp
export FW_CONFIG_FILE=/global/home/users/fxie/atomate_config/config/FW_config.yaml

cd /global/scratch/users/fxie/alli_bcc_launch/block_2023-08-26-01-12-11-451865/launcher_2023-08-26-01-12-28-217863
rlaunch -c /global/home/users/fxie/atomate_config/config singleshot

# CommonAdapter (SLURM) completed writing Template

`

**Comment by qchempku2017** [comment]
> Can you please confirm the output of `_openmp_effective_numthreads()` and `_openmp_effective_numthreads(2)` in the cluster you are running (you can import it from `smol.utils._openmp_helpers`)

The result obtained from LRC login node:
>>> from smol.utils._openmp_helpers import _openmp_effective_numthreads
>>> _openmp_effective_numthreads()
32
>>> _openmp_effective_numthreads(2)
2
>>>

**Comment by qchempku2017** [comment]
Currently, testing both of the following methods failed:

(1) Changing OMP_NUM_THREADS to 2 in head node environment variables takes no effect on the atomate2 workflow behavior at all.
(2) Changing OMP_NUM_THREADS to 2 in submission script (by modifying my_qadapter.yaml) would result in the failure of  VASP due to unknown process dead-locking issue.

As a result, I recommend implementing one of the following solutions:
(1) Changing the default behavior of _omp_effective_numthreads to yielding 1. If the users wish to use multiprocessing in order to evaluate correlation functions, they may need to explicitly specify num_threads > 1 when initializing relevant objects.
 (2) Adding num_threads to the savings and loadings in from_dict and as_dict. This is necessary since each time when atomate2 completes a job, the output object will be saved into mongodb by from_dict and then the child jobs read from mongodb using as_dict. If the num_threads parameter is not saved, when the object is initialized again during load, num_threads might be initialized as a new default value, causing incompatibility with the current running environment.

What do you think @lbluque ?

**Comment by qchempku2017** [comment]
Or would you mind having another check on the default logic of _openmp_default_numthreads?
Here is what you wrote, basically, if the input numthreads is a positive integer, you will always return that number, because the return of L78 is just the original num_threads without any modification:
[_openmp_helper.pyx](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/_openmp_helpers.pyx#L78)
The usage of this function happens in [numthreads.py(L6 and L37)](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/cluster/numthreads.py#L6), where you set DEFAULT_NUM_THREADS with argument num_threads=2, which means your default will always be 2. However, when the system OMP_NUM_THREADS is 1, you will have serious mistake as your max_num_threads is returned by using _openmp_default_numthreads with argument num_threads=None, which will return 1. This will create a conflict and pausing the code.

**If this is the mistake, you can also change [_openmp_helper.pyx(L78)](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/_openmp_helpers.pyx#L78) to properly returning something like min(max_n_threads, n_threads), etc.** @lbluque

**Comment by lbluque** [comment]
Thanks for investigating @qchempku2017.

I am still not convinced this is a bug or that this warrants changing the source code here. Perhaps with the exception of adding error handling in `from_dict`.

To solve your issue I think you need to make sure that the OMP settings wherever your smol object is created match the ones where you are running code using it.  For example in your case since you need to have OMP_NUM_THREADS=1 in the compute node so that VASP runs correctly, then  set OMP_NUM_THREADS=1 or directly specify `num_threads=1` in the smol object, in the login node (or wherever you are creating the automate workflows)

**Comment by qchempku2017** [comment]
Sorry for being a bit annoying here but _openmp_default_numthreads might not be doing what we believed it would do. When there is only one OMP THREAD available, the DEFAULT_NUM_THREADS variable should be set to 1 instead of 2. Would you mind giving any comment on that behavior? I guess this could be the key.

**Comment by qchempku2017** [comment]
[    - For ``n_threads > 0``, return this as the maximal number of threads for
      parallel OpenMP calls.](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/_openmp_helpers.pyx#L48C1-L49C29)

**Comment by lbluque** [comment]
> Or would you mind having another check on the default logic of _openmp_default_numthreads? Here is what you wrote, basically, if the input numthreads is a positive integer, you will always return that number, because the return of L78 is just the original num_threads without any modification: [_openmp_helper.pyx](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/_openmp_helpers.pyx#L78) The usage of this function happens in [numthreads.py(L6 and L37)](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/cluster/numthreads.py#L6), where you set DEFAULT_NUM_THREADS with argument num_threads=2, which means your default will always be 2. However, when the system OMP_NUM_THREADS is 1, you will have serious mistake as your max_num_threads is returned by using _openmp_default_numthreads with argument num_threads=None, which will return 1. This will create a conflict and pausing the code.
> 
> **If this is the mistake, you can also change [_openmp_helper.pyx(L78)](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/_openmp_helpers.pyx#L78) to properly returning something like min(max_n_threads, n_threads), etc.** @lbluque

I see this should be change to return the min of those two, or simply always return OMP_NUM_THREADS if set

**Comment by qchempku2017** [comment]
> > Or would you mind having another check on the default logic of _openmp_default_numthreads? Here is what you wrote, basically, if the input numthreads is a positive integer, you will always return that number, because the return of L78 is just the original num_threads without any modification: [_openmp_helper.pyx](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/_openmp_helpers.pyx#L78) The usage of this function happens in [numthreads.py(L6 and L37)](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/cluster/numthreads.py#L6), where you set DEFAULT_NUM_THREADS with argument num_threads=2, which means your default will always be 2. However, when the system OMP_NUM_THREADS is 1, you will have serious mistake as your max_num_threads is returned by using _openmp_default_numthreads with argument num_threads=None, which will return 1. This will create a conflict and pausing the code.
> > **If this is the mistake, you can also change [_openmp_helper.pyx(L78)](https://github.com/CederGroupHub/smol/blob/ce61c5a14b1f38661504444392b37b8bd218b9cd/smol/utils/_openmp_helpers.pyx#L78) to properly returning something like min(max_n_threads, n_threads), etc.** @lbluque
> 
> I see this should be change to return the min of those two, or simply always return OMP_NUM_THREADS if set

Thanks man! I'm sorry for being so dumb and reckless at explaining but I'm happy to finally get my ideas through!

**Comment by lbluque** [comment]
fixed in #404
