### ISSUE TITLE
Supercell could not be found from structure

### ISSUE THREAD

**Issue by ghalibalfaza** [CederGroupHub/smol#407]
Dear everyone, I am a beginner here 

## Expected Behavior
The correlation vector can be calculated

## Current Behavior
I tried to make a CE from scratch, using rocksalt structure (Fm̅3m) as the primitive cell and I prepared 3 relaxed structure as my training data with the supercell's size is 2x2x2. However, There is an error message when I tried to calculate the correlation vector

StructureMatchError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_10576/2246665970.py in <module>
      1 structure = entries[0]
----> 2 corr = subspace.corr_from_structure(structure)

~\anaconda3\lib\site-packages\smol\cofe\space\clusterspace.py in corr_from_structure(self, structure, normalized, scmatrix, site_mapping)
    682         """
    683         if scmatrix is None:
--> 684             scmatrix = self.scmatrix_from_structure(structure)
    685 
    686         occu = self.occupancy_from_structure(

~\anaconda3\lib\site-packages\smol\cofe\space\clusterspace.py in scmatrix_from_structure(self, structure)
    833         scmatrix = self._sc_matcher.get_supercell_matrix(structure, self.structure)
    834         if scmatrix is None:
--> 835             raise StructureMatchError("Supercell could not be found from structure")
    836         if np.linalg.det(scmatrix) < 0:
    837             scmatrix *= -1

StructureMatchError: Supercell could not be found from structure

## Possible Solution
Is there any rule that I should follow to make the primitive cell and the training data?

**Comment by lbluque** [comment]
Hi @ghalibalfaza :wave: 

Can you give use more information on how you created the `ClusterSubspace`?

Can you copy the output of printing your disordered primitive structure?

If your DFT structures undergo large relaxations, you may also need to play around with the tolerances passed to the [`pymatgen.StructureMatcher`](https://pymatgen.org/pymatgen.analysis.html#pymatgen.analysis.structure_matcher.StructureMatcher)

**Comment by ghalibalfaza** [comment]
Hello Dr. Barroso-Luque, please find the attached file which consists of 3 files: one jupyter notebook and 2 JSON files (the primitive cell and the training data). Any help would be greatly appreciated, thank you so much.
[CE_Test.zip](https://github.com/CederGroupHub/smol/files/12494644/CE_Test.zip)

**Comment by ghalibalfaza** [comment]
Hello Dr. Barroso-Luque, please find the attached file which consists of 3 files: one jupyter notebook and 2 JSON files (the primitive cell and the training data). Any help would be greatly appreciated, thank you so much.
[CE_test.zip](https://github.com/CederGroupHub/smol/files/12494656/CE_test.zip)

**Comment by lbluque** [comment]
Hi @ghalibalfaza 

I had a look at your notebook.

The issues is you are using `supercell_size="O2-"` in your `ClusterSubspace` as the method to determine supercell sizes, which means it will try to determine the supercell size from the total number of O2- present. But since your structure has O/F disorder this is not appropriate because the number of O2- can be different for the same supercell.

Since you don't have any vacancies, I recommend using `supercell_size="num_sites"`, this will determine supercell size based on the total number of sites.

**Comment by lbluque** [comment]
I assume this resolved your issue. Closing, but feel free to reopen if this has not been solved.
