### ISSUE TITLE
[Bug]: SampleContainer previously saved as .h5 cannot be loaded - values corresponding to "accepted" key in Trace returns NoneType

### ISSUE THREAD

**Issue by kamronald** [CederGroupHub/smol#441]
### Email (Optional)

kamronald@berkeley.edu

### Version

v0.5.3

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

When attempting to open a SampleContainer previously saved to a .h5 file, the following error comes up:
`TypeError: 'NoneType' object is not subscriptable`
This arises because the values of the "accepted" key of the saved Trace instance has been deleted, which I confirmed from opening the file with h5py. However, the values corresponding to the other keys (ie "features", "enthalpy", "occupancy", "temperature") remain there, which is quite bizarre and puzzling to me. Another important point is that I had previously opened these files and collected the data without any issue. So somewhere along the way, the "accepted" data must have been corrupted somehow. Just speculating, but could this be an issue with opening these files using h5py without using SWMR mode?

This issue has come up for me in the past, but I had not documented it here. Previously I found that the SampleContainers saved after fully updating the code were not problematic, so I just recovered the data in the bad .h5 files from opening with h5py. However, this time there are a lot of SampleContainers with lots of data that have this issue, so I need to find a more permanent solution to this.
The SampleContainer is located at this Google drive link, as it is too large to be uploaded onto Github: https://drive.google.com/file/d/1AXGLUw5lD1IenkC8XqZvPrsV72vSFJpF/view?usp=sharing

### Code snippet

```python
# To reproduce the error from opening the SampleContainer
from smol.moca.sampler.container import SampleContainer
samples = SampleContainer.from_hdf5('gcmc_11.0ev_1000k.h5')

# To open the .h5 file using hdf5:
import h5py
with h5py.File('gcmc_11.25ev_1000k.h5', "r") as f:
   print('Number of sampled features saved:', len(f['trace']['features']))
   print('Attempting to access the acceptances array')
   print(len(f['trace']['accepted']))
```

### Log output

```shell
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 samples = SampleContainer.from_hdf5('gcmc_11.0ev_1000k.h5')

File ~/miniconda3/envs/stat_mech/lib/python3.9/site-packages/monty/dev.py:113, in requires.__call__.<locals>.decorated(*args, **kwargs)
    111 if not self.condition:
    112     raise RuntimeError(self.message)
--> 113 return _callable(*args, **kwargs)

File ~/Software/smol/smol/moca/sampler/container.py:657, in SampleContainer.from_hdf5(cls, file_path, swmr_mode, ensemble)
    648 if len(f["trace"]["occupancy"]) > nsamples:
    649     warnings.warn(
    650         f"The hdf5 file provided appears to be from an unifinished"
    651         f" MC run.\n Only {nsamples} of "
   (...)
    654         UserWarning,
    655     )
    656 trace = Trace(
--> 657     **{name: value[:nsamples] for name, value in f["trace"].items()}
    658 )
    660 if "sublattices" in f.keys():  # legacy file
    661     sampling_metadata = json.loads(
    662         f["sampling_metadata"][()], cls=MontyDecoder
    663     )

File ~/Software/smol/smol/moca/sampler/container.py:657, in <dictcomp>(.0)
    648 if len(f["trace"]["occupancy"]) > nsamples:
    649     warnings.warn(
    650         f"The hdf5 file provided appears to be from an unifinished"
    651         f" MC run.\n Only {nsamples} of "
   (...)
    654         UserWarning,
    655     )
    656 trace = Trace(
--> 657     **{name: value[:nsamples] for name, value in f["trace"].items()}
    658 )
    660 if "sublattices" in f.keys():  # legacy file
    661     sampling_metadata = json.loads(
    662         f["sampling_metadata"][()], cls=MontyDecoder
    663     )

TypeError: 'NoneType' object is not subscriptable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lbluque** [comment]
Hi @kamronald :wave: thanks for reporting this. 

When you said you had previously been able to collect data from the files, what was the general workflow? Did the simulation end and afterwards you opened the container using `from_hdf5` or directly with h5py? Or did you open before the simulation had ended?

Can you send me a minimal working example of the script you used to run the simulations? (I don't need the details of your CE, just the general workflow you used)

**Comment by kamronald** [comment]
Yes this is currently how I run GCMC simulations over multiple chemical potentials
```
for mu in mu_search:
        chemical_potentials["Li+"] = mu
        ensemble.chemical_potentials = chemical_potentials
        this_sampler = Sampler.from_ensemble(ensemble,
                                         step_type='table-flip',
                                         temperature=temperature,
                                         optimize_basis=True,
                                         swap_weight=0.2
                                         )

        this_sampler.run(nsteps=iters_to_run,
                         initial_occupancies=init_occu,
                         thin_by=100,
                         #progress=True,
                         stream_chunk=10,
                         stream_file=mc_path
                         )

        del this_sampler
        these_samples = SampleContainer.from_hdf5(mc_path)
        this_num_samples = these_samples.num_samples
        init_occu = these_samples.get_occupancies(discard=this_num_samples-100)[-1]
```

**Comment by kamronald** [comment]
For collecting the data, I open the file using `from_hdf5` after the simulation ends. Something like this:

data_d = {}
for file in mc_path:
   container = SampleContainer.from_hdf5(file)
   avg_comp = container.mean_composition(discard=20000)
   avg_en = container.mean_enthalpy(discard=20000)
   data_d[file] = {'avg_en': avg_en, 'avg_comp': avg_comp}

**Comment by kamronald** [comment]
As it turns out, simply updating h5py to the latest version has solved the issue!
