### ISSUE TITLE
[Feature Request]: Release the constraint of bits

### ISSUE THREAD

**Issue by Jeff-oakley** [CederGroupHub/smol#461]
### Email (Optional)

bouyang@fsu.edu

### Problem

It is indicated in the initial function of Orbit that 
`
bits (list of list):
                list describing the possible site function indices for
                each site in cluster. Should be the number of possible
                occupancies minus one. For a 3 site cluster, each of which
                can have one of Li, TM, or Vac, bits are [[0, 1], [0, 1], [0, 1]]
                This is ensures the expansion is not "over-complete" by
                implicitly enforcing that all sites have a site basis function
                phi_0 = 1.
`
How can I get rid of such constraint and set bits as [[0,1,2],[0,1,2],[0,1,2]] instead for the case above?

### Proposed Solution

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kamronald** [comment]
Hi @Jeff-oakley, if you want to use an overcomplete basis, the PottsSubspace is an overcomplete indicator basis, if you are interested in using that functionality. Otherwise if you want an over-complete sinusoid or other type of basis, then we don't have that implemented

**Comment by Jeff-oakley** [comment]
> Hi @Jeff-oakley, if you want to use an overcomplete basis, the PottsSubspace is an overcomplete indicator basis, if you are interested in using that functionality. Otherwise if you want an over-complete sinusoid or other type of basis, then we don't have that implemented

I see. That is good to know. I will check out for that. Thank you.
