### ISSUE TITLE
[Bug]:  smol.moca.SampleContainer requested more memory than the specified number of steps.

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/smol#481]
### Email (Optional)

fengyu_xie@berkeley.edu

### Version

v0.5.4

### Which OS(es) are you using?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### What happened?

When performing a canonical simulaton of 10000 steps, smol.moca.sampler actually allocated 11000 steps in memory. This leads to all last 1000 energies and occupancies being 0. 
This is not really a bug, but if some users might want to access the final structure using get_occupancies()[-1]. With the current behavior, the will get an error. We may need to either change this behavior or warn the users about it in the docs.
Not sure if this problem is specific to windows.

### Code snippet

```python
ca_sampler = Sampler.from_ensemble(ca_ensemble, temperature=2000)
ca_sampler.run(10000, initial_occupancies=np.array([init_occu]))
len(ca_sampler.samples), ca_sampler.samples.get_occupancies()[-1]
```

### Log output

```shell
(11000,
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kamronald** [comment]
Hi @qchempku2017 thanks for brining this up. I tried to reproduce your issue on MacOS but was unable to. Used pretty much the same code snippet but the number of samples is consistent:

Code snippet:
```
sampler = Sampler.from_ensemble(ensemble, temperature=1000)
sampler.run(1000, initial_occupancies=init_occus)
len(sampler.samples), sampler.samples.get_occupancies()[-1]
```

Output:
```
(1000,
 array([0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]))
```

Also tried it on Ubuntu for Windows on my PC, and it also looks fine. Perhaps it is only a windows issue?

**Comment by qchempku2017** [comment]
> Hi @qchempku2017 thanks for brining this up. I tried to reproduce your issue on MacOS but was unable to. Used pretty much the same code snippet but the number of samples is consistent:
> 
> Code snippet:
> 
> ```
> sampler = Sampler.from_ensemble(ensemble, temperature=1000)
> sampler.run(1000, initial_occupancies=init_occus)
> len(sampler.samples), sampler.samples.get_occupancies()[-1]
> ```
> 
> Output:
> 
> ```
> (1000,
>  array([0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
>         0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>         0, 0, 0, 0, 0, 0]))
> ```
> 
> Also tried it on Windows Subsystem for Linux (WSL) on my PC, and it also looks fine. Perhaps it is only a windows issue?
> 
> Output on WSL:
> 
> ```
> (1000,
>  array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
>         1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
>         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>         0, 0, 0, 0, 0, 0]))
> ```

I suspect so... If things work out fine I think we just need to remind the users to take care when using smol to simulate on windows in the doc string or the doc pages.
