### ISSUE TITLE
Enable user-specified spin flips to canonical MC

### ISSUE THREAD

**Issue by juliayang** [CederGroupHub/smol#52]
**Is your feature request related to a problem? Please describe.**
There are some examples which require modification to the way spin flips are currently implemented: 

1. Species which can exist on different sublattices should be flipped. For example, Li+ exists in both tetrahedral or octahedral sites. Therefore, Li+ on sublattice 1 (tetrahedral) or sublattice 2 (octahedral) should be allowed to flip between the two. Currently a Li+ on sublattice 1 will only be allowed to flip within sublattice 1. 
2. Mn disproportionation are relevant in some systems. Therefore, Mn3+ and Mn3+ on sublattice 1 should be allowed to flip to Mn2+ and Mn4+ on sublattice 1 (or to another sublattice). 

It has been suggested by Gerd to include a feature where a user can specify allowed perturbations since it seems that other perturbations, besides for the two examples above, may want to be enforced. 

**Describe the solution you'd like**
Ideally, user specifies a table of allowed perturbations and a probability by which the perturbation can occur. In example 1, a user could specify: `{'Li+': {'sublattice_1': 0.5}, {'sublattice_2': 0.5}}` indicating that a Li+ can equally flip into sublattice 1 or sublattice 2. The code will then enforce that such possible flips are picked with equal probability.

Note that detailed balance should be obeyed at all times, which could be either up the user, or the code, to enforce. 

**Describe alternatives you've considered**
@tchen0965 has code which can address the first issue of Li+ spin flips between different sublattices. She may want to submit a PR soon.

**Comment by lbluque** [comment]
I'm closing this since it seems to have largely been addressed in #271
